/**
 * Catálogo de assets generados en Fase 3 (Nanobanana).
 * Los archivos viven en web/public/brand/manual-assets/{social,ads,decks,imagery,icons}/.
 */

export type ManualAsset = {
  id: string;
  title: string;
  description: string;
  src: string;
  aspect: string;
  platform: string;
  dimensions: string;
};

export const socialAssets: ManualAsset[] = [
  {
    id: "ig-feed-hero",
    title: "IG Feed — Hero",
    description: "Primer post de serie, formato hero visual con copy en bottom 30%.",
    src: "/brand/manual-assets/social/ig-feed-hero.png",
    aspect: "4/5",
    platform: "Instagram",
    dimensions: "1080×1350",
  },
  {
    id: "ig-feed-split",
    title: "IG Feed — Split",
    description: "Contraste boutique vs commodity. Bueno para storytelling visual.",
    src: "/brand/manual-assets/social/ig-feed-split.png",
    aspect: "4/5",
    platform: "Instagram",
    dimensions: "1080×1350",
  },
  {
    id: "ig-feed-quote",
    title: "IG Feed — Quote",
    description: "Template para pull-quotes y frases core.",
    src: "/brand/manual-assets/social/ig-feed-quote.png",
    aspect: "4/5",
    platform: "Instagram",
    dimensions: "1080×1350",
  },
  {
    id: "ig-story-hook",
    title: "IG Story — Hook",
    description: "Primera story de secuencia, enfoca la atención arriba.",
    src: "/brand/manual-assets/social/ig-story-hook.png",
    aspect: "9/16",
    platform: "Instagram",
    dimensions: "1080×1920",
  },
  {
    id: "ig-story-behind",
    title: "IG Story — BTS",
    description: "Behind the scenes del set real, documentary.",
    src: "/brand/manual-assets/social/ig-story-behind.png",
    aspect: "9/16",
    platform: "Instagram",
    dimensions: "1080×1920",
  },
  {
    id: "ig-reel-cover",
    title: "IG Reel — Cover",
    description: "Cover frame para Reels; mantiene la atención en el primer tap.",
    src: "/brand/manual-assets/social/ig-reel-cover.png",
    aspect: "9/16",
    platform: "Instagram",
    dimensions: "1080×1920",
  },
  {
    id: "tiktok-tutorial",
    title: "TikTok — Tutorial cover",
    description: "Workspace minimalista con warm desk lamp. Ideal para tips.",
    src: "/brand/manual-assets/social/tiktok-tutorial.png",
    aspect: "9/16",
    platform: "TikTok",
    dimensions: "1080×1920",
  },
  {
    id: "tiktok-testimonial",
    title: "TikTok — Testimonial cover",
    description: "Soft amber rim suggesting documentary interview.",
    src: "/brand/manual-assets/social/tiktok-testimonial.png",
    aspect: "9/16",
    platform: "TikTok",
    dimensions: "1080×1920",
  },
  {
    id: "linkedin-post",
    title: "LinkedIn — Post",
    description: "B2B corporate square. Performance chart abstracto.",
    src: "/brand/manual-assets/social/linkedin-post.png",
    aspect: "1/1",
    platform: "LinkedIn",
    dimensions: "1200×1200",
  },
  {
    id: "linkedin-banner",
    title: "LinkedIn — Banner",
    description: "Profile cover con executive premium look.",
    src: "/brand/manual-assets/social/linkedin-banner.png",
    aspect: "16/9",
    platform: "LinkedIn",
    dimensions: "1584×396",
  },
  {
    id: "youtube-thumb",
    title: "YouTube — Thumbnail",
    description: "Editorial dark con right 40% clean para título.",
    src: "/brand/manual-assets/social/youtube-thumb.png",
    aspect: "16/9",
    platform: "YouTube",
    dimensions: "1280×720",
  },
  {
    id: "youtube-banner",
    title: "YouTube — Channel banner",
    description: "Ultra-wide minimal; safe zone al centro.",
    src: "/brand/manual-assets/social/youtube-banner.png",
    aspect: "16/9",
    platform: "YouTube",
    dimensions: "2560×1440",
  },
];

export const adsAssets: ManualAsset[] = [
  {
    id: "meta-1x1",
    title: "Meta — Feed 1:1",
    description: "Stopping power inicial para ads Meta cuadrados.",
    src: "/brand/manual-assets/ads/meta-1x1.png",
    aspect: "1/1",
    platform: "Meta",
    dimensions: "1080×1080",
  },
  {
    id: "meta-4x5",
    title: "Meta — Feed 4:5",
    description: "Formato dominante en Meta feed móvil.",
    src: "/brand/manual-assets/ads/meta-4x5.png",
    aspect: "4/5",
    platform: "Meta",
    dimensions: "1080×1350",
  },
  {
    id: "meta-9x16",
    title: "Meta — Story/Reel 9:16",
    description: "Vertical para stories y reels sponsored.",
    src: "/brand/manual-assets/ads/meta-9x16.png",
    aspect: "9/16",
    platform: "Meta",
    dimensions: "1080×1920",
  },
  {
    id: "google-1200x628",
    title: "Google Display — 1200×628",
    description: "Responsive banner, horizontal ancho.",
    src: "/brand/manual-assets/ads/google-1200x628.png",
    aspect: "16/9",
    platform: "Google",
    dimensions: "1200×628",
  },
  {
    id: "google-300x250",
    title: "Google MREC — 300×250",
    description: "Display pequeño, alta rotación.",
    src: "/brand/manual-assets/ads/google-300x250.png",
    aspect: "4/5",
    platform: "Google",
    dimensions: "300×250",
  },
  {
    id: "tiktok-hook",
    title: "TikTok Ad — Hook",
    description: "First-frame pause-scroll moment.",
    src: "/brand/manual-assets/ads/tiktok-hook.png",
    aspect: "9/16",
    platform: "TikTok",
    dimensions: "1080×1920",
  },
  {
    id: "tiktok-social-proof",
    title: "TikTok Ad — Social Proof",
    description: "Sense of momentum abstracto.",
    src: "/brand/manual-assets/ads/tiktok-social-proof.png",
    aspect: "9/16",
    platform: "TikTok",
    dimensions: "1080×1920",
  },
  {
    id: "tiktok-cta",
    title: "TikTok Ad — CTA frame",
    description: "Frame de cierre con space para CTA.",
    src: "/brand/manual-assets/ads/tiktok-cta.png",
    aspect: "9/16",
    platform: "TikTok",
    dimensions: "1080×1920",
  },
];

export const deckAssets: ManualAsset[] = [
  {
    id: "deck-portada",
    title: "01 · Portada",
    description: "Diagonal amber ray. Slide de apertura del pitch.",
    src: "/brand/manual-assets/decks/01-portada.png",
    aspect: "16/9",
    platform: "Deck",
    dimensions: "1920×1080",
  },
  {
    id: "deck-problema",
    title: "02 · Problema",
    description: "Visualiza content fatigue.",
    src: "/brand/manual-assets/decks/02-problema.png",
    aspect: "16/9",
    platform: "Deck",
    dimensions: "1920×1080",
  },
  {
    id: "deck-solucion",
    title: "03 · Solución",
    description: "Spotlight sobre la propuesta boutique.",
    src: "/brand/manual-assets/decks/03-solucion.png",
    aspect: "16/9",
    platform: "Deck",
    dimensions: "1920×1080",
  },
  {
    id: "deck-servicios",
    title: "04 · Servicios",
    description: "5 íconos en línea para overview del portafolio.",
    src: "/brand/manual-assets/decks/04-servicios.png",
    aspect: "16/9",
    platform: "Deck",
    dimensions: "1920×1080",
  },
  {
    id: "deck-pricing",
    title: "05 · Pricing",
    description: "3 columnas con plan destacado al centro.",
    src: "/brand/manual-assets/decks/05-pricing.png",
    aspect: "16/9",
    platform: "Deck",
    dimensions: "1920×1080",
  },
  {
    id: "deck-cta",
    title: "06 · CTA",
    description: "Slide de cierre con room para statement.",
    src: "/brand/manual-assets/decks/06-cta.png",
    aspect: "16/9",
    platform: "Deck",
    dimensions: "1920×1080",
  },
];

export const imageryAssets: ManualAsset[] = [
  {
    id: "hero-lifestyle",
    title: "Hero Lifestyle",
    description: "Interior boutique studio con luz amber.",
    src: "/brand/manual-assets/imagery/hero-lifestyle.png",
    aspect: "16/9",
    platform: "Brand",
    dimensions: "1920×1080",
  },
  {
    id: "bts-estudio",
    title: "BTS Estudio",
    description: "Ring light en foco, equipment en segundo plano.",
    src: "/brand/manual-assets/imagery/bts-estudio.png",
    aspect: "3/2",
    platform: "Brand",
    dimensions: "1800×1200",
  },
  {
    id: "creators-pool",
    title: "Creators Pool",
    description: "Silueta de red de creadores.",
    src: "/brand/manual-assets/imagery/creators-pool.png",
    aspect: "16/9",
    platform: "Brand",
    dimensions: "1920×1080",
  },
  {
    id: "mesa-trabajo",
    title: "Mesa de trabajo",
    description: "Flat-lay editorial de workspace creator.",
    src: "/brand/manual-assets/imagery/mesa-trabajo.png",
    aspect: "3/2",
    platform: "Brand",
    dimensions: "1800×1200",
  },
  {
    id: "equipo-boutique",
    title: "Equipo Boutique",
    description: "Sala de reunión boutique golden hour.",
    src: "/brand/manual-assets/imagery/equipo-boutique.png",
    aspect: "16/9",
    platform: "Brand",
    dimensions: "1920×1080",
  },
  {
    id: "producto-en-uso",
    title: "Producto en uso",
    description: "Testimonial aesthetic sin mostrar cara.",
    src: "/brand/manual-assets/imagery/producto-en-uso.png",
    aspect: "4/5",
    platform: "Brand",
    dimensions: "1080×1350",
  },
];

export const iconAssets: ManualAsset[] = [
  { id: "icon-strategy", title: "Strategy", description: "Compass monoline.", src: "/brand/manual-assets/icons/strategy.png", aspect: "1/1", platform: "Icon", dimensions: "1024×1024" },
  { id: "icon-performance", title: "Performance", description: "Rising chart line.", src: "/brand/manual-assets/icons/performance.png", aspect: "1/1", platform: "Icon", dimensions: "1024×1024" },
  { id: "icon-creators", title: "Creators", description: "Tres círculos red.", src: "/brand/manual-assets/icons/creators.png", aspect: "1/1", platform: "Icon", dimensions: "1024×1024" },
  { id: "icon-matching", title: "Matching", description: "Flechas intercambio.", src: "/brand/manual-assets/icons/matching.png", aspect: "1/1", platform: "Icon", dimensions: "1024×1024" },
  { id: "icon-production", title: "Production", description: "Clapperboard de rodaje.", src: "/brand/manual-assets/icons/production.png", aspect: "1/1", platform: "Icon", dimensions: "1024×1024" },
  { id: "icon-ads", title: "Ads", description: "Megáfono minimal.", src: "/brand/manual-assets/icons/ads.png", aspect: "1/1", platform: "Icon", dimensions: "1024×1024" },
  { id: "icon-platform", title: "Platform", description: "Capas apiladas (Kreoon).", src: "/brand/manual-assets/icons/platform.png", aspect: "1/1", platform: "Icon", dimensions: "1024×1024" },
  { id: "icon-quality", title: "Quality", description: "Check dentro de círculo.", src: "/brand/manual-assets/icons/quality.png", aspect: "1/1", platform: "Icon", dimensions: "1024×1024" },
];
